### ISSUE TITLE
Index page text should be justified.

### ISSUE THREAD

**Issue by SkyzohKey** [Tox/tox.chat#69]
Hey guys, I was browsing the current beta of tox.chat on m'y smartphone and saw an horrible thing : centered texts. This is really ugly and it should be justified. 

Screenshot of uglyness: http://imgur.com/M8Tizqg

ie.
```css
p {
  text-align: justify;
}
```
